
services:
  salazarapp:
    image: openai-demo-app
    container_name: salazar-concept-app
    restart: unless-stopped
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    # ports:
    #   - "3000:3000"
    networks:
      - proxy

  salazarapi:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: salazar-concept-api
    restart: unless-stopped
    # ports:
    #   - "8090:8090"
    volumes:
      - ./api:/api
      - ./api/data:/pb_data
    networks:
      - proxy

networks:
  proxy:
    external: true
