version: '3.5'

services:
  app:
    image: openai-demo-app
    container_name: salazar-concept-app
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"

  api:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: salazar-concept-api
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./api:/api
      - ./api/data:/pb_data
